// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooManagementDB;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(ZooManagementDBContext))]
    [Migration("20250606095632_DBContextSeeding")]
    partial class DBContextSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ZooManagement.Animal", b =>
                {
                    b.Property<int>("AnimalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivedAtZoo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT");

                    b.Property<string>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Species")
                        .HasColumnType("TEXT");

                    b.HasKey("AnimalID");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalID = 1,
                            DOB = "09/10/2021",
                            Name = "Ed",
                            Sex = 0,
                            Species = "Lion"
                        },
                        new
                        {
                            AnimalID = 2,
                            DOB = "08/12/2015",
                            Name = "Mary",
                            Sex = 0,
                            Species = "Elephant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
