// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooManagementDB;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(ZooManagementDBContext))]
    partial class ZooManagementDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ZooManagement.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivedAtZoo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT");

                    b.Property<string>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnclosureID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .HasColumnType("TEXT");

                    b.HasKey("AnimalId");

                    b.HasIndex("EnclosureID");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("ZooManagement.Enclosure", b =>
                {
                    b.Property<int>("EnclosureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnclosureName")
                        .HasColumnType("TEXT");

                    b.HasKey("EnclosureID");

                    b.ToTable("Enclosure");
                });

            modelBuilder.Entity("ZooManagement.Animal", b =>
                {
                    b.HasOne("ZooManagement.Enclosure", "enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("enclosure");
                });

            modelBuilder.Entity("ZooManagement.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
